# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-15 21:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='message',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='message_html',
            field=models.TextField(default='', editable=False),
        ),
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together=set([('user', 'message')]),
        ),
    ]
